// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: proto/config.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ConfigService_ConfigLongRunning_FullMethodName = "/config.ConfigService/ConfigLongRunning"
	ConfigService_Flaky_FullMethodName             = "/config.ConfigService/Flaky"
	ConfigService_GetServerAddress_FullMethodName  = "/config.ConfigService/GetServerAddress"
)

// ConfigServiceClient is the client API for ConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigServiceClient interface {
	ConfigLongRunning(ctx context.Context, in *ConfigLongRunningRequest, opts ...grpc.CallOption) (*ConfigLongRunningResponse, error)
	Flaky(ctx context.Context, in *FlakyRequest, opts ...grpc.CallOption) (*FlakyResponse, error)
	GetServerAddress(ctx context.Context, in *GetServerAddressRequest, opts ...grpc.CallOption) (*GetServerAddressResponse, error)
}

type configServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigServiceClient(cc grpc.ClientConnInterface) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) ConfigLongRunning(ctx context.Context, in *ConfigLongRunningRequest, opts ...grpc.CallOption) (*ConfigLongRunningResponse, error) {
	out := new(ConfigLongRunningResponse)
	err := c.cc.Invoke(ctx, ConfigService_ConfigLongRunning_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) Flaky(ctx context.Context, in *FlakyRequest, opts ...grpc.CallOption) (*FlakyResponse, error) {
	out := new(FlakyResponse)
	err := c.cc.Invoke(ctx, ConfigService_Flaky_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetServerAddress(ctx context.Context, in *GetServerAddressRequest, opts ...grpc.CallOption) (*GetServerAddressResponse, error) {
	out := new(GetServerAddressResponse)
	err := c.cc.Invoke(ctx, ConfigService_GetServerAddress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigServiceServer is the server API for ConfigService service.
// All implementations must embed UnimplementedConfigServiceServer
// for forward compatibility
type ConfigServiceServer interface {
	ConfigLongRunning(context.Context, *ConfigLongRunningRequest) (*ConfigLongRunningResponse, error)
	Flaky(context.Context, *FlakyRequest) (*FlakyResponse, error)
	GetServerAddress(context.Context, *GetServerAddressRequest) (*GetServerAddressResponse, error)
	mustEmbedUnimplementedConfigServiceServer()
}

// UnimplementedConfigServiceServer must be embedded to have forward compatible implementations.
type UnimplementedConfigServiceServer struct {
}

func (UnimplementedConfigServiceServer) ConfigLongRunning(context.Context, *ConfigLongRunningRequest) (*ConfigLongRunningResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigLongRunning not implemented")
}
func (UnimplementedConfigServiceServer) Flaky(context.Context, *FlakyRequest) (*FlakyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Flaky not implemented")
}
func (UnimplementedConfigServiceServer) GetServerAddress(context.Context, *GetServerAddressRequest) (*GetServerAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerAddress not implemented")
}
func (UnimplementedConfigServiceServer) mustEmbedUnimplementedConfigServiceServer() {}

// UnsafeConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigServiceServer will
// result in compilation errors.
type UnsafeConfigServiceServer interface {
	mustEmbedUnimplementedConfigServiceServer()
}

func RegisterConfigServiceServer(s grpc.ServiceRegistrar, srv ConfigServiceServer) {
	s.RegisterService(&ConfigService_ServiceDesc, srv)
}

func _ConfigService_ConfigLongRunning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigLongRunningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).ConfigLongRunning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_ConfigLongRunning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).ConfigLongRunning(ctx, req.(*ConfigLongRunningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_Flaky_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlakyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).Flaky(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_Flaky_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).Flaky(ctx, req.(*FlakyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetServerAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetServerAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_GetServerAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetServerAddress(ctx, req.(*GetServerAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigService_ServiceDesc is the grpc.ServiceDesc for ConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "config.ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfigLongRunning",
			Handler:    _ConfigService_ConfigLongRunning_Handler,
		},
		{
			MethodName: "Flaky",
			Handler:    _ConfigService_Flaky_Handler,
		},
		{
			MethodName: "GetServerAddress",
			Handler:    _ConfigService_GetServerAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/config.proto",
}
