// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: proto/interceptor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	InterceptorService_Unprotected_FullMethodName = "/interceptor.InterceptorService/Unprotected"
	InterceptorService_Protected_FullMethodName   = "/interceptor.InterceptorService/Protected"
)

// InterceptorServiceClient is the client API for InterceptorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InterceptorServiceClient interface {
	Unprotected(ctx context.Context, in *UnprotectedRequest, opts ...grpc.CallOption) (*UnprotectedResponse, error)
	Protected(ctx context.Context, in *ProtectedRequest, opts ...grpc.CallOption) (*ProtectedResponse, error)
}

type interceptorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInterceptorServiceClient(cc grpc.ClientConnInterface) InterceptorServiceClient {
	return &interceptorServiceClient{cc}
}

func (c *interceptorServiceClient) Unprotected(ctx context.Context, in *UnprotectedRequest, opts ...grpc.CallOption) (*UnprotectedResponse, error) {
	out := new(UnprotectedResponse)
	err := c.cc.Invoke(ctx, InterceptorService_Unprotected_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interceptorServiceClient) Protected(ctx context.Context, in *ProtectedRequest, opts ...grpc.CallOption) (*ProtectedResponse, error) {
	out := new(ProtectedResponse)
	err := c.cc.Invoke(ctx, InterceptorService_Protected_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InterceptorServiceServer is the server API for InterceptorService service.
// All implementations must embed UnimplementedInterceptorServiceServer
// for forward compatibility
type InterceptorServiceServer interface {
	Unprotected(context.Context, *UnprotectedRequest) (*UnprotectedResponse, error)
	Protected(context.Context, *ProtectedRequest) (*ProtectedResponse, error)
	mustEmbedUnimplementedInterceptorServiceServer()
}

// UnimplementedInterceptorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInterceptorServiceServer struct {
}

func (UnimplementedInterceptorServiceServer) Unprotected(context.Context, *UnprotectedRequest) (*UnprotectedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unprotected not implemented")
}
func (UnimplementedInterceptorServiceServer) Protected(context.Context, *ProtectedRequest) (*ProtectedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Protected not implemented")
}
func (UnimplementedInterceptorServiceServer) mustEmbedUnimplementedInterceptorServiceServer() {}

// UnsafeInterceptorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InterceptorServiceServer will
// result in compilation errors.
type UnsafeInterceptorServiceServer interface {
	mustEmbedUnimplementedInterceptorServiceServer()
}

func RegisterInterceptorServiceServer(s grpc.ServiceRegistrar, srv InterceptorServiceServer) {
	s.RegisterService(&InterceptorService_ServiceDesc, srv)
}

func _InterceptorService_Unprotected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnprotectedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterceptorServiceServer).Unprotected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterceptorService_Unprotected_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterceptorServiceServer).Unprotected(ctx, req.(*UnprotectedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterceptorService_Protected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtectedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterceptorServiceServer).Protected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterceptorService_Protected_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterceptorServiceServer).Protected(ctx, req.(*ProtectedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InterceptorService_ServiceDesc is the grpc.ServiceDesc for InterceptorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InterceptorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interceptor.InterceptorService",
	HandlerType: (*InterceptorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unprotected",
			Handler:    _InterceptorService_Unprotected_Handler,
		},
		{
			MethodName: "Protected",
			Handler:    _InterceptorService_Protected_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/interceptor.proto",
}
